### ISSUE TITLE
Conficts with mod "Build Info" (while looking at block that has locked component)

### ISSUE THREAD

**Issue by Akuukis** [Equinox-/SEProceduralWorld#6]
514062285.sbm_BuildInfo/info.log
```
[10:27:59] ERROR: System.NullReferenceException: Object reference not set to an instance of an object.
   at Digi.BuildInfo.Extensions.AppendMaxLength(StringBuilder s, String text, Int32 maxLength)
   at Digi.BuildInfo.Extensions.ModFormat(StringBuilder s, MyModContext context)
   at Digi.BuildInfo.BuildInfo.GenerateBlockText(MyCubeBlockDefinition def)
```

I was just wondering if that's easy to solve, and should be solved on this side at all.

**Comment by Akuukis** [comment]
wrong repo
