### ISSUE TITLE
random SE crash after ~1min while configuring `aux_research.xml`

### ISSUE THREAD

**Issue by Akuukis** [Equinox-/SEProceduralWorld#7]
SpaceEngineers.log
```
2018-05-01 10:35:29.771 - Thread:   1 ->  Exception occured: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Equinox.Utils.PlayerCollection.<Refresh>b__14_0(IMyPlayer x)
   at Sandbox.Game.Multiplayer.MyPlayerCollection.VRage.Game.ModAPI.IMyPlayerCollection.GetPlayers(List`1 players, Func`2 collect)
   at Equinox.Utils.PlayerCollection.Refresh()
   at Equinox.Utils.PlayerCollection.<>c__DisplayClass13_0.<PlayerConnected>b__0()
   at Sandbox.MySandboxGame.ProcessInvoke()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass1.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
```

Unfortunately I can't reproduce it anymore.

**Comment by Akuukis** [comment]
wrong repo
